news/urls.py
from django.conf.urls import url
from . import views

app_name = 'news'
urlpatterns = [
    url(r'^(?P<page>[0-9]+)/$', views.Index.as_view(), name='index'),
    url(r'^filter/(?P<option>.+)/(?P<variable>.+)/$', views.CategoryTagView.as_view(), name='filter'),
    url(r'^detail/(?P<pk>[0-9]+)/$', views.Detail.as_view(), name='detail'),
    url(r'(?P<article_id>[0-9]+)/add_comment', views.add_comment, name='add_comment'),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from news import views  # Django freaks because no top level import like from ../news import views
from project.settings import TEMPLATE_PREFIX as TP

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^news/', include('news.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='account/'+TP+'/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name='news/'+TP+'/index.html'), name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'about/$', views.about, name='about'),
    url(r'contact_us/', views.contact_us, name='contact_us'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
from django.db import models
from django.utils.timezone import now
from news.models import Article # Django freaks because no top level import like from ../news import
# Create your models here.


class Comment(models.Model):
    author = models.CharField(max_length=100)
    comment_text = models.TextField(max_length=300)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(default=now)

    def __str__(self):
        return '\n Author: %s \n Publication Date: %s \n Comment: %s ' % (self.author, self.pub_date, self.comment_text)

news/models.py
from django.db import models
# Create your models here.
TITLE_MAX_LENGTH = 90
TAG_MAX_LENGTH = 30


class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    pub_date = models.DateTimeField()
    article_text = models.TextField()
    image_url = models.URLField(default='media/article_images/default.jpg')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return "\n Title: %s \n Publication date: %s \n Category: %s" % \
                (self.title, self.pub_date, self.category.name)


class Tags(models.Model):
    tag = models.CharField(max_length=TAG_MAX_LENGTH)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str__(self):
        return "TAG: %s ARTICLE: %s" % (self.tag, self.article.title)

news/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from .models import Article, Category, Tags
from django.db import Error
from django.utils.datastructures import MultiValueDictKeyError
from django.contrib.auth.decorators import login_required
from project.settings import TEMPLATE_PREFIX as TP

# Create your views here.


class Index(generic.ListView):

    model = Article
    allow_empty = True
    template_name = "news/"+TP+"/index.html"
    context_object_name = "articles"
    paginate_by = 10

    def get_queryset(self):
        return Article.objects.order_by('-pub_date')

    # def get_context_data(self, **kwargs):
    #     context = super(ArticleListView, self).get_context_data(**kwargs)
    #     context['now'] = timezone.now()
    #     return context TODO: for complex view


class Detail(generic.DetailView):

    model = Article
    template_name = "news/"+TP+"/detail.html"
    context_object_name = "article"

    # def get_context_data(self, **kwargs):
    #     context = super(Detail, self).get_context_data(**kwargs)
    #     #context['article'] = context['article'].comment_set.order_by('-pub_date')
    #     return context


class CategoryTagView(generic.ListView):

    model = Article
    allow_empty = True
    template_name = "news/"+TP+"/index.html"
    context_object_name = "articles"
    paginate_by = 10

    def get_queryset(self):
        if self.kwargs['option'] == 'category':
            cat = Category.objects.get(name=str(self.kwargs['variable']))
            return Article.objects.filter(category=cat).order_by('-pub_date')
        elif self.kwargs['option'] == 'tag':
            return Article.objects.filter(tags__tag=self.kwargs['variable']).order_by('-pub_date')

@login_required
def add_comment(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    if request.POST['comment_text'] == '':
        return render(request, 'news/'+TP+'/detail.html', {
            'article': article,
            'error_message': "You didn't enter text.",
        })
    else:
        try:
            article.comment_set.create(author=request.user.username, comment_text=request.POST['comment_text'],
                                       pub_date=timezone.now())
            article.save()
            return HttpResponseRedirect(reverse('news:detail', args=(article_id,)))
        except Error:
            return render(request, 'news/'+TP+'/detail.html', {
                'article': article,
                'error_message': "Can't add comment.",
            })


def about(request):
    return render(request, 'site/'+TP+'/about.html')


def contact_us(request):
    return render(request, 'site/' + TP + '/contact_us.html')

news/templates/news/base_v0/detail.html
{% extends "../../site/base_v0/base.html" %}

{% block meta_description %} {{article.article_text|truncatechars_html:"160"}} {% endblock %}

{% block title %} {{article.title}}PROJECT T.A.N.G.O. (game news) {% endblock %}

{% block og_seo %}
    <meta property="og:title" content="{{article.title}}" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="{% url 'news:detail' article.id %}" />
    <meta property="og:image" content="{{article.image_url}}" />
    <meta property="article:published_time" content="{{article.pub_date}}" />
    <meta property="article:section " content="{{article.category.name}}" />
    {% for tag in article.tags_set.all %}
    <meta property="article:tag" content="{{tag.tag}}" />
    {% endfor %}
{% endblock %}

{% block main %}
{% load static %}
 <section class="row justify-content-start">
    <div class="col-12 d-flex align-items-center">
      <article itemscope itemtype="http://schema.org/Article">
                      <div class="d-none" itemprop="publisher" itemscope itemtype="https://schema.org/Organization">
                        <div itemprop="logo" itemscope itemtype="https://schema.org/ImageObject">
                            <img src="{% static 'news/base_v0/logo.jpg' %}"/>
                            <meta itemprop="url" content="{% static 'news/base_v0/logo.jpg' %}">
                            <meta itemprop="width" content="1107">
                            <meta itemprop="height" content="386">
                        </div>
                        <meta itemprop="name" content="PROJECT T.A.N.G.O. (game news)">
                      </div>
                    <section class="row justify-content-center">
                      <div class="col-12 d-flex flex-wrap text-center" itemprop="author" content="PROJECT T.A.N.G.O. (game news)">
                        <h5 class="my-0 border-bottom-line w-100" itemprop="headline"><a itemprop="mainEntityOfPage" content="{% url 'news:detail' article.id %}" href="{% url 'news:detail' article.id %}">{{article.title}}</a></h5>
                      </div>
                    </section>
                    <section class="row">
                      <div class="col-12 d-flex flex-wrap flex-md-nowrap flex-lg-nowrap">
                          <h6 class="p-1 pl-1">Category:<a href="{% url 'news:filter' 'category' article.category.name %}">{{article.category.name}}</a></h6>
                        <h6 class="p-1">Tags:{% for tag in article.tags_set.all %}
                            <a href="{% url 'news:filter' 'tag' tag.tag %}">{{ tag.tag }}</a>
                                                   {% endfor %}</h6>
                        <h6 class="p-1 mr-auto" itemprop="interactionStatistic" itemscope itemtype="http://schema.org/InteractionCounter" content="{{article.comment_set.count}}">Comments:{{article.comment_set.count}}</h6>
                        <h6 class="p-1 pr-3 pr-md-0" itemprop="datePublished" content="{{article.pub_date}}">Pub_date:{{article.pub_date}}</h6>
                      </div>
                    </section>
                    <section class="row">
                      <div class="col-12 d-flex flex-column flex-wrap">
                        <img class="img-fluid align-self-center w-75 border-img" itemprop="image" src="{{article.image_url}}" alt="{{article.title}}">
                        <div class="mx-auto pl-1" itemprop="description">{{article.article_text|safe}}
                        </div>
                      </div>
                    </section>
          <section class="row">
              <div class="col-12 d-flex flex-column flex-nowrap align-items-center px-md-4 mx-md-2">
                <h6 class="align-self-start">
                  Add comment:
                </h6>
                {% if error_message %}
                  <br> <h6 class="alert alert-danger" role="alert">{{error_message}}</h6>
                {% endif %}
                  <form action="{% url 'news:add_comment' article.id %}" class="col-12 d-flex flex-column " method="post">
                  {% csrf_token %}
                  <div class="form-group my-1">
                   <textarea class="form-control" name="comment_text" rows="3"></textarea>
                  </div>
                    <button type="submit" class="btn btn-red border-red align-self-center">Send</button>
                  </form>
              </div>
          </section>
          <section class="row">
              <div class="col-12 d-flex flex-column flex-wrap mx-1 mx-sm-2 mx-md-3 mx-lg-4">
                 <h6> Comments({{article.comment_set.count}})</h6>

                  {% for comment in article.comment_set.all %}
                        <div> Author: {{comment.author}}</div>
                        <div> Publication Date: {{comment.pub_date}}</div>
                        <div class="word-break">{{comment.comment_text}}</div>
                  {% endfor %}
              </div>
          </section>
       </article>
   </div>
 </section>
{% endblock %}

news/templates/news/base_v0/index.html
{% extends "../../site/base_v0/base.html" %}

{% block meta_description %} News Page PROJECT T.A.N.G.O. (game news) - fast loading game news website {% endblock %}

{% block title %} News Page PROJECT T.A.N.G.O. (game news) - fast loading game news website {% endblock %}

{% block main %}
{% load static %}
            <section class="row justify-content-start">
            <div class="col-12 d-flex align-items-center">
              <ul class="list-unstyled">
                {% for article in articles.all %}
                <li>
                  <article itemscope itemtype="http://schema.org/Article">
                      <div class="d-none" itemprop="publisher" itemscope itemtype="https://schema.org/Organization">
                        <div itemprop="logo" itemscope itemtype="https://schema.org/ImageObject">
                            <img src="{% static 'news/base_v0/logo.jpg' %}"/>
                            <meta itemprop="url" content="{% static 'news/base_v0/logo.jpg' %}">
                            <meta itemprop="width" content="1107">
                            <meta itemprop="height" content="386">
                        </div>
                        <meta itemprop="name" content="PROJECT T.A.N.G.O. (game news)">
                      </div>
                    <section class="row justify-content-center">
                      <div class="col-12 d-flex flex-wrap text-center" itemprop="author" content="PROJECT T.A.N.G.O. (game news)">
                        <h5 class="my-0 border-bottom-line w-100" itemprop="headline"><a itemprop="mainEntityOfPage" content="{% url 'news:detail' article.id %}" href="{% url 'news:detail' article.id %}">{{article.title}}</a></h5>
                      </div>
                    </section>
                    <section class="row">
                      <div class="col-12 d-flex flex-wrap flex-md-nowrap flex-lg-nowrap">
                          <h6 class="p-1 pl-1">Category:<a href="{% url 'news:filter' 'category' article.category.name %}">{{article.category.name}}</a></h6>
                        <h6 class="p-1">Tags:{% for tag in article.tags_set.all %}
                            <a href="{% url 'news:filter' 'tag' tag.tag %}">{{ tag.tag }}</a>
                                                   {% endfor %}</h6>
                        <h6 class="p-1 mr-auto" itemprop="interactionStatistic" itemscope itemtype="http://schema.org/InteractionCounter" content="{{article.comment_set.count}}">Comments:{{article.comment_set.count}}</h6>
                        <h6 class="p-1 pr-3 pr-md-0" itemprop="datePublished" content="{{article.pub_date}}">Pub_date:{{article.pub_date}}</h6>
                      </div>
                    </section>
                    <section class="row">
                      <div class="col-12 d-flex flex-column flex-wrap">
                        <img class="img-fluid align-self-center w-75 border-img" itemprop="image" src="{{article.image_url}}" alt="{{article.title}}">
                        <div class="mx-auto pl-1" itemprop="description">{{article.article_text|safe|truncatechars_html:"160"}}
                           <br> <a href="{% url 'news:detail' article.id %}"> Continue read -></a>
                        </div>
                      </div>
                    </section>
                  </article>
                </li>
                {% endfor %}
              </ul>
            </div>
            </section>
         {% if is_paginated %}
            <section class="row">
              <div class="col-12 d-flex justify-content-center">
                <nav aria-label="Pagination" >
                <ul class="pagination border-bottom-line">
                  <li class="page-item  text-color-primary">
                    <a class="page-link border-0" {% if page_obj.has_previous %}
                                            href="{% url 'news:index' page_obj.previous_page_number %}"
                                         {% else %}
                                            href="#" tabindex="-1"
                                         {% endif %}
                                         >Previous</a>
                  </li>
                  <li class="page-item">
                    <a class="page-link border-0" {% if page_obj.has_next %}
                                            href="{% url 'news:index' page_obj.next_page_number %}"
                                         {% else %}
                                            href="#" tabindex="-1"
                                         {% endif %}
                                         >Next</a>
                  </li>
                 </ul>
              </nav>
              </div>
            </section>
         {% endif %}
            {% endblock %}