news/urls.py
from django.conf.urls import url
from . import views

app_name = 'news'
urlpatterns = [
    url(r'^(?P<page>[0-9]+)/$', views.Index.as_view(), name='index'),
    url(r'^filter/(?P<option>.+)/(?P<variable>.+)/$', views.CategoryTagView.as_view(), name='filter'),
    url(r'^detail/(?P<pk>[0-9]+)/$', views.Detail.as_view(), name='detail'),
    url(r'(?P<article_id>[0-9]+)/add_comment', views.add_comment, name='add_comment'),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from news import views  # Django freaks because no top level import like from ../news import views
from project.settings import TEMPLATE_PREFIX as TP

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^news/', include('news.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='account/'+TP+'/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name='news/'+TP+'/index.html'), name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'about/$', views.about, name='about'),
    url(r'contact_us/', views.contact_us, name='contact_us'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybb/account/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from pybb.account.views import SignupView, LoginView, LogoutView, DeleteView
from pybb.account.views import ConfirmEmailView
from pybb.account.views import ChangePasswordView, PasswordResetView, PasswordResetTokenView
from pybb.account.views import SettingsView


urlpatterns = [
    url(r"^signup/$", SignupView.as_view(), name="account_signup"),
    url(r"^login/$", LoginView.as_view(), name="account_login"),
    url(r"^logout/$", LogoutView.as_view(), name="account_logout"),
    url(r"^confirm_email/(?P<key>\w+)/$", ConfirmEmailView.as_view(), name="account_confirm_email"),
    url(r"^password/$", ChangePasswordView.as_view(), name="account_password"),
    url(r"^password/reset/$", PasswordResetView.as_view(), name="account_password_reset"),
    url(r"^password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$", PasswordResetTokenView.as_view(), name="account_password_reset_token"),
    url(r"^settings/$", SettingsView.as_view(), name="account_settings"),
    url(r"^delete/$", DeleteView.as_view(), name="account_delete"),
]

pybb/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf.urls import url

from pybb.defaults import PYBB_NICE_URL
from pybb.feeds import LastPosts, LastTopics
from pybb.views import IndexView, CategoryView, ForumView, TopicView, \
    AddPostView, EditPostView, MovePostView, UserView, PostView, ProfileEditView, \
    DeletePostView, StickTopicView, UnstickTopicView, CloseTopicView, \
    OpenTopicView, ModeratePost, TopicPollVoteView, LatestTopicsView, \
    UserTopics, UserPosts, topic_cancel_poll_vote, block_user, unblock_user, \
    delete_subscription, add_subscription, post_ajax_preview, \
    mark_all_as_read, ForumSubscriptionView, UserEditPrivilegesView

from pybb.forms import SignupFormWithCaptcha
from django.contrib import admin
from pybb.account.views import ChangePasswordView, SignupView, LoginView

app_name = 'pybbm'

urlpatterns = [
    # Syndication feeds
    url('^feeds/posts/$', LastPosts(), name='feed_posts'),
    url('^feeds/topics/$', LastTopics(), name='feed_topics'),
]

urlpatterns += [
    # Index, Category, Forum
    url('^$', IndexView.as_view(), name='index'),
    url('^category/(?P<pk>\d+)/$', CategoryView.as_view(), name='category'),
    url('^forum/(?P<pk>\d+)/$', ForumView.as_view(), name='forum'),
    url(r"^accounts/signup/$",
        SignupView.as_view(form_class=SignupFormWithCaptcha),
        name="registration_register"),
    url(r"^accounts/login/$", LoginView.as_view(), name="auth_login"),

    # User
    url('^users/(?P<username>[^/]+)/$', UserView.as_view(), name='user'),
    url('^block_user/([^/]+)/$', block_user, name='block_user'),
    url('^unblock_user/([^/]+)/$', unblock_user, name='unblock_user'),
    url(r'^users/(?P<username>[^/]+)/topics/$', UserTopics.as_view(),
        name='user_topics'),
    url(r'^users/(?P<username>[^/]+)/posts/$', UserPosts.as_view(),
        name='user_posts'),
    url(r'^users/(?P<username>[^/]+)/edit-privileges/$',
        UserEditPrivilegesView.as_view(), name='edit_privileges'),

    # Profile
    url('^profile/edit/$', ProfileEditView.as_view(), name='edit_profile'),

    # Topic
    url('^topic/(?P<pk>\d+)/$', TopicView.as_view(), name='topic'),
    url('^topic/(?P<pk>\d+)/stick/$', StickTopicView.as_view(),
        name='stick_topic'),
    url('^topic/(?P<pk>\d+)/unstick/$', UnstickTopicView.as_view(),
        name='unstick_topic'),
    url('^topic/(?P<pk>\d+)/close/$', CloseTopicView.as_view(),
        name='close_topic'),
    url('^topic/(?P<pk>\d+)/open/$', OpenTopicView.as_view(),
        name='open_topic'),
    url('^topic/(?P<pk>\d+)/poll_vote/$', TopicPollVoteView.as_view(),
        name='topic_poll_vote'),
    url('^topic/(?P<pk>\d+)/cancel_poll_vote/$', topic_cancel_poll_vote,
        name='topic_cancel_poll_vote'),
    url('^topic/latest/$', LatestTopicsView.as_view(), name='topic_latest'),

    # Add topic/post
    url('^forum/(?P<forum_id>\d+)/topic/add/$', AddPostView.as_view(),
        name='add_topic'),
    url('^topic/(?P<topic_id>\d+)/post/add/$', AddPostView.as_view(),
        name='add_post'),

    # Post
    url('^post/(?P<pk>\d+)/$', PostView.as_view(), name='post'),
    url('^post/(?P<pk>\d+)/edit/$', EditPostView.as_view(), name='edit_post'),
    url('^post/(?P<pk>\d+)/move/$', MovePostView.as_view(), name='move_post'),
    url('^post/(?P<pk>\d+)/delete/$', DeletePostView.as_view(),
        name='delete_post'),
    url('^post/(?P<pk>\d+)/moderate/$', ModeratePost.as_view(),
        name='moderate_post'),

    # Attachment
    # url('^attachment/(\w+)/$', 'show_attachment', name='pybb_attachment'),

    # Subscription
    url('^subscription/topic/(\d+)/delete/$',
        delete_subscription, name='delete_subscription'),
    url('^subscription/topic/(\d+)/add/$',
        add_subscription, name='add_subscription'),
    url('^subscription/forum/(?P<pk>\d+)/$',
        ForumSubscriptionView.as_view(), name='forum_subscription'),

    # API
    url('^api/post_ajax_preview/$', post_ajax_preview,
        name='post_ajax_preview'),

    # Commands
    url('^mark_all_as_read/$', mark_all_as_read, name='mark_all_as_read')
]

if PYBB_NICE_URL:
    urlpatterns += [
        url(r'^c/(?P<slug>[\w-]+)/$', CategoryView.as_view(), name='category'),
        url(r'^c/(?P<category_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
            ForumView.as_view(),
            name='forum'),
        url(
            r'^c/(?P<category_slug>[\w-]+)/(?P<forum_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
            TopicView.as_view(), name='topic'),
    ]

pybb/account/views.py
from __future__ import unicode_literals

from django.http import Http404, HttpResponseForbidden
from django.shortcuts import redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.utils.http import base36_to_int, int_to_base36
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic.base import TemplateResponseMixin, View
from django.views.generic.edit import FormView

from django.contrib import auth, messages
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site

from pybb.account import signals
from pybb.account.compat import reverse, is_authenticated
from pybb.account.conf import settings
from pybb.account.forms import SignupForm, LoginUsernameForm
from pybb.account.forms import ChangePasswordForm, PasswordResetForm, PasswordResetTokenForm
from pybb.account.forms import SettingsForm
from pybb.account.hooks import hookset
from pybb.account.mixins import LoginRequiredMixin
from pybb.account.models import SignupCode, EmailAddress, EmailConfirmation, Account, AccountDeletion, PasswordHistory
from pybb.account.utils import default_redirect, get_form_data


class PasswordMixin(object):
    """
    Mixin handling common elements of password change.

    Required attributes in inheriting class:

      form_password_field - example: "password"
      fallback_url_setting - example: "ACCOUNT_PASSWORD_RESET_REDIRECT_URL"

    Required methods in inheriting class:

      get_user()
      change_password()
      after_change_password()
      get_redirect_field_name()

    """

    redirect_field_name = "next"
    messages = {
        "password_changed": {
            "level": messages.SUCCESS,
            "text": _("Password successfully changed.")
        }
    }

    def get_context_data(self, **kwargs):
        ctx = super(PasswordMixin, self).get_context_data(**kwargs)
        redirect_field_name = self.get_redirect_field_name()
        ctx.update({
            "redirect_field_name": redirect_field_name,
            "redirect_field_value": self.request.POST.get(redirect_field_name, self.request.GET.get(redirect_field_name, "")),
        })
        return ctx

    def change_password(self, form):
        user = self.get_user()
        user.set_password(form.cleaned_data[self.form_password_field])
        user.save()
        return user

    def after_change_password(self):
        user = self.get_user()
        signals.password_changed.send(sender=self, user=user)
        if settings.ACCOUNT_NOTIFY_ON_PASSWORD_CHANGE:
            self.send_password_email(user)
        if self.messages.get("password_changed"):
            messages.add_message(
                self.request,
                self.messages["password_changed"]["level"],
                self.messages["password_changed"]["text"]
            )

    def get_redirect_field_name(self):
        return self.redirect_field_name

    def get_success_url(self, fallback_url=None, **kwargs):
        if fallback_url is None:
            fallback_url = getattr(settings, self.fallback_url_setting, None)
        kwargs.setdefault("redirect_field_name", self.get_redirect_field_name())
        return default_redirect(self.request, fallback_url, **kwargs)

    def send_password_email(self, user):
        protocol = getattr(settings, "DEFAULT_HTTP_PROTOCOL", "http")
        current_site = get_current_site(self.request)
        ctx = {
            "user": user,
            "protocol": protocol,
            "current_site": current_site,
        }
        hookset.send_password_change_email([user.email], ctx)

    def create_password_history(self, form, user):
        if settings.ACCOUNT_PASSWORD_USE_HISTORY:
            password = form.cleaned_data[self.form_password_field]
            PasswordHistory.objects.create(
                user=user,
                password=make_password(password)
            )


class SignupView(PasswordMixin, FormView):

    template_name = "account/signup.html"
    template_name_ajax = "account/ajax/signup.html"
    template_name_email_confirmation_sent = "account/email_confirmation_sent.html"
    template_name_email_confirmation_sent_ajax = "account/ajax/email_confirmation_sent.html"
    template_name_signup_closed = "account/signup_closed.html"
    template_name_signup_closed_ajax = "account/ajax/signup_closed.html"
    form_class = SignupForm
    form_kwargs = {}
    form_password_field = "password"
    redirect_field_name = "next"
    identifier_field = "username"
    messages = {
        "email_confirmation_sent": {
            "level": messages.INFO,
            "text": _("Confirmation email sent to {email}.")
        },
        "invalid_signup_code": {
            "level": messages.WARNING,
            "text": _("The code {code} is invalid.")
        }
    }
    fallback_url_setting = "ACCOUNT_SIGNUP_REDIRECT_URL"

    def __init__(self, *args, **kwargs):
        self.created_user = None
        kwargs["signup_code"] = None
        super(SignupView, self).__init__(*args, **kwargs)

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        self.args = args
        self.kwargs = kwargs
        self.setup_signup_code()
        return super(SignupView, self).dispatch(request, *args, **kwargs)

    def setup_signup_code(self):
        code = self.get_code()
        if code:
            try:
                self.signup_code = SignupCode.check_code(code)
            except SignupCode.InvalidCode:
                self.signup_code = None
            self.signup_code_present = True
        else:
            self.signup_code = None
            self.signup_code_present = False

    def get(self, *args, **kwargs):
        if is_authenticated(self.request.user):
            return redirect(default_redirect(self.request, settings.ACCOUNT_LOGIN_REDIRECT_URL))
        if not self.is_open():
            return self.closed()
        return super(SignupView, self).get(*args, **kwargs)

    def post(self, *args, **kwargs):
        if is_authenticated(self.request.user):
            raise Http404()
        if not self.is_open():
            return self.closed()
        return super(SignupView, self).post(*args, **kwargs)

    def get_initial(self):
        initial = super(SignupView, self).get_initial()
        if self.signup_code:
            initial["code"] = self.signup_code.code
            if self.signup_code.email:
                initial["email"] = self.signup_code.email
        return initial

    def get_template_names(self):
        if self.request.is_ajax():
            return [self.template_name_ajax]
        else:
            return [self.template_name]

    def get_form_kwargs(self):
        kwargs = super(SignupView, self).get_form_kwargs()
        kwargs.update(self.form_kwargs)
        return kwargs

    def form_invalid(self, form):
        signals.user_sign_up_attempt.send(
            sender=SignupForm,
            username=get_form_data(form, self.identifier_field),
            email=get_form_data(form, "email"),
            result=form.is_valid()
        )
        return super(SignupView, self).form_invalid(form)

    def form_valid(self, form):
        self.created_user = self.create_user(form, commit=False)
        # prevent User post_save signal from creating an Account instance
        # we want to handle that ourself.
        self.created_user._disable_account_creation = True
        self.created_user.save()
        self.use_signup_code(self.created_user)
        email_address = self.create_email_address(form)
        if settings.ACCOUNT_EMAIL_CONFIRMATION_REQUIRED and not email_address.verified:
            self.created_user.is_active = False
            self.created_user.save()
        self.create_account(form)
        self.create_password_history(form, self.created_user)
        self.after_signup(form)
        if settings.ACCOUNT_EMAIL_CONFIRMATION_EMAIL and not email_address.verified:
            self.send_email_confirmation(email_address)
        if settings.ACCOUNT_EMAIL_CONFIRMATION_REQUIRED and not email_address.verified:
            return self.email_confirmation_required_response()
        else:
            show_message = [
                settings.ACCOUNT_EMAIL_CONFIRMATION_EMAIL,
                self.messages.get("email_confirmation_sent"),
                not email_address.verified
            ]
            if all(show_message):
                messages.add_message(
                    self.request,
                    self.messages["email_confirmation_sent"]["level"],
                    self.messages["email_confirmation_sent"]["text"].format(**{
                        "email": form.cleaned_data["email"]
                    })
                )
            # attach form to self to maintain compatibility with login_user
            # API. this should only be relied on by d-u-a and it is not a stable
            # API for site developers.
            self.form = form
            self.login_user()
        return redirect(self.get_success_url())

    def create_user(self, form, commit=True, model=None, **kwargs):
        User = model
        if User is None:
            User = get_user_model()
        user = User(**kwargs)
        username = form.cleaned_data.get("username")
        if username is None:
            username = self.generate_username(form)
        user.username = username
        user.email = form.cleaned_data["email"].strip()
        password = form.cleaned_data.get("password")
        if password:
            user.set_password(password)
        else:

pybb/templates/pybb/_button_new_topic.html
{% load i18n %}<a href="{% url 'pybb:add_topic' forum.id %}" class="new-topic h5 px-3">{% trans 'New topic' %}</a>

pybb/templates/pybb/_markitup_preview.html
<html>
<head>
    <style type="text/css">
        blockquote {
          padding: 0 0 0 15px;
          margin: 0 0 20px;
          border-left: 5px solid #eeeeee;
        }
        pre {
            display: block;
            padding: 9.5px;
            margin: 0 0 10px;
            font-size: 13px;
            line-height: 20px;
            word-break: break-all;
            word-wrap: break-word;
            white-space: pre;
            white-space: pre-wrap;
            background-color: whiteSmoke;
            border: 1px solid #CCC;
            border: 1px solid rgba(0, 0, 0, 0.15);
            -webkit-border-radius: 4px;
            -moz-border-radius: 4px;
            border-radius: 4px;
        }
    </style>
</head>
<body>
{{ html|safe }}
</body>
</html>

pybb/templates/pybb/add_post.html
{% extends 'pybb/base.html' %}
{% load i18n pybb_tags staticfiles %}

{% block title %}
{% if forum %}{% trans 'New topic' %}{% else %}{% trans 'New reply' %}{% endif %}
{% endblock %}

{% block extra_head %}
    {{ block.super }}
    {{ form.media.css }}
{% endblock %}
{% block extra_script %}
    {{ block.super }}
    {{ form.media.js }}
    <script type="text/javascript" src="{% static 'pybb/js/jquery.formset.min.js' %}"></script>
{% endblock %}

{% block breadcrumb %}
    {% if forum %}
        {% with object=forum extra_crumb="New topic" %}
            {% include 'pybb/breadcrumb.html' %}
        {% endwith %}
    {% else %}
        {% with object=topic extra_crumb="New reply" %}
            {% include 'pybb/breadcrumb.html' %}
        {% endwith %}
    {% endif %}
{% endblock %}

{% block content %}

<h2 class="col-md-12 d-flex justify-content-center">{% if forum %}{% trans 'New topic' %}{% else %}{% trans 'New reply' %}{% endif %}</h2>

<div class="d-flex justify-content-center">{% include "pybb/post_form.html" %}</div>
{% endblock content %}

pybb/templates/pybb/avatar.html
{% load pybb_tags %}
<div class="avatar row justify-content-center col-12">
    {% pybb_get_profile user=user as user_profile %}
    <a href="{{ user_profile.get_absolute_url }}">
        {% if user_profile.avatar %}
            {% if 'sorl.thumbnail'|check_app_installed %}
                {% include 'pybb/_sorl_thumbnail_avatar.html' %}
            {% elif 'easy_thumbnails'|check_app_installed %}
                {% include 'pybb/_easy_thumbnail_avatar.html' %}
            {% else %}
                <img src="{{ user_profile.avatar.url }}" alt="{{ user_profile.get_display_name }} avatar" width="{{ PYBB_AVATAR_WIDTH }}" height="{{ PYBB_AVATAR_HEIGHT }}"/>
            {% endif %}
        {% else %}
            <img src="{{ PYBB_DEFAULT_AVATAR_URL }}" alt="default avatar" width="{{ PYBB_AVATAR_WIDTH }}" height="{{ PYBB_AVATAR_HEIGHT }}"/>
        {% endif %}
    </a>
</div>

pybb/templates/pybb/delete_post.html
{% extends 'pybb/base.html' %}
{% load i18n pybb_tags %}

{% block content %}
    <h3 class="row justify-content-center py-2">{% trans 'Are you sure you want to delete this message?' %}</h3>
    <div class="post-preview well row justify-content-center">
       "{{ post.body_html|safe }}"
    </div>
    <form method="post" action=".">
        {% csrf_token %}
        <p class="row justify-content-md-center col-md-12">
            <div class="row justify-content-center">
                <a class="h5 py-1" href="{{ post.get_absolute_url }}">← {% trans 'No, take me back' %}</a>
            </div>
            <div class="row justify-content-center">
            <input type="submit" class="btn btn-red row justify-content-center" value="{% trans 'Yes, I am sure' %}" />
            </div>
        </p>
    </form>
{% endblock content %}

pybb/templates/pybb/edit_privileges.html
{% extends 'pybb/base.html' %}

{% load i18n pybb_tags %}

{% block title %}{% trans 'Grant moderator privileges' %}{% endblock title %}

{% block content %}
    <h2 class="col-12 d-flex justify-content-center py-1">{% trans 'Grant moderator privileges' %}</h2>
        <form method="post" action="" class="privileges-edit col-12">
            {% csrf_token %}
            <fieldset>
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                    {% for field in form %}
                        {% if field.auto_id %}
                            <label class="control-label {% if field.field.required %}{{ form.required_css_class }}{% endif %}" for="{{ field.auto_id }}">{{ field.label }}</label>
                        {% endif %}

                        <div class="multiple-checkbox">
                            {{ field }}

                            {% for error in field.errors %}
                                <span class="help-block {{ form.error_css_class }}">{{ error }}</span>
                            {% endfor %}

                            {% if field.help_text %}
                                <p class="help-block">
                                    {{ field.help_text|safe }}
                                </p>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
            </fieldset>
            <p class="col-12 row justify-content-center">{% include "pybb/_button_save.html" %}</p>
        </form>
{% endblock content %}

pybb/templates/pybb/form_errors.html
{% if form.non_field_errors %}
    {{ form.non_field_errors }}
{% endif %}
{% if form.non_form_errors %}
    {{ form.non_form_errors }}
{% endif %}

pybb/templates/pybb/form_field.html
{% load pybb_tags %}

<div class="{% if field.is_required %}required{% endif %} {% if field.errors %}error{% endif %}">
    {% if not hide_labels or hide_labels == 0 %}
        <label for="{{ field.auto_id }}" class="d-flex justify-content-center">
            {{ field.field.label }}
        </label>
    {% endif %}
    <div class="d-flex justify-content-center">
        {{ field }}
        {% for error in field.errors %}
            <span class="field-errors">{{ field.errors }}</span>
        {% endfor %}
    </div>
</div>

pybb/templates/pybb/forum_list.html
{% load pybb_tags i18n %}

{% if forum_list %}
    <table class="table d-flex flex-column d-md-table {% if category %}category-table{% elif parent_forum %}child-forums-table{% endif %} col-md-12 p-0">
        <thead>
            <tr class="forum-row head-row">
                <th class="forum-name col p-2">
                    {% trans 'Forum' %}
                </th>
                <th class="forum-topic-count col p-2">
                    {% trans 'Topics' %}
                </th>
                <th class="forum-post-count col p-2">
                    {% trans 'Posts' %}
                </th>
                <th class="forum-last-post col p-2 px-md-5">
                    {% trans 'Last posts' %}
                </th>
            </tr>
        </thead>
        <tbody>
        {% for forum in forum_list|pybb_forum_unread:user %}
            <tr class="forum-row">
                <td class="forum-name {% if forum.unread %} forum-unread{% endif %} col p-2">
                    <a href="{{ forum.get_absolute_url }}">{{ forum.name }}</a> {% if forum.hidden %}[{% trans 'Hidden' %}]{% endif %}
                    <div class="forum-description">
                        {{ forum.description|safe }}
                    </div>
                </td>
                <td class="forum-topic-count col p-2">
                    {{ forum.topic_count }}
                </td>
                <td class="forum-post-count col p-2">
                    {{ forum.post_count }}
                </td>
                <td class="forum-last-post col p-2 px-md-0">
                    {% include "pybb/forum_last_update_info.html" %}
                </td>
            </tr>
        {% empty %}
            {% if category %}
                <h3 class="row justify-content-center">{% trans 'No forums created' %}</h3>
                <a href="{% url 'admin:pybb_forum_add' %}">{% trans 'Add forum now' %}</a>
            {%  endif %}
        {% endfor %}
        </tbody>
    </table>
{% endif %}

pybb/templates/pybb/index.html
{% extends 'pybb/base.html' %}

{% load i18n %}

{% block title %}{{ PYBB_DEFAULT_TITLE }}{% endblock title %}

{% block breadcrumb %}
    {% with extra_crumb="Forum" %}{% include "pybb/breadcrumb.html" %}{% endwith %}
{% endblock %}

{% block content %}
    {% if categories %}
        {% for category in categories %}
            {% include 'pybb/category.html' %}
        {% endfor %}
    {% else %}
        <h2>{% trans 'Forum categories are not created' %}</h2>
        <a href="{% url 'admin:pybb_category_add' %}">{% trans 'Add a category now' %}</a>
    {% endif %}
    {% if user.is_authenticated %}
        <div id="mark-all-as-read" class="row justify-content-center">
            <a class="h5" href="{% url 'pybb:topic_latest' %}">{% trans 'Last updates in topics' %}</a> /
            <a class="h5" href="{% url 'pybb:mark_all_as_read' %}">{% trans 'Mark all forums as read' %}</a>
        </div>
    {% endif %}
{% endblock content %}

pybb/templates/pybb/latest_topics.html
{% extends 'pybb/base.html' %}

{% load pybb_tags i18n %}

{% block title %}{% trans 'Last updates in topics' %}{% endblock title %}

{% block breadcrumb %}
    {% with extra_crumb=_("Last updates in topics") %}
        {% include "pybb/breadcrumb.html" %}
    {% endwith %}
{% endblock %}

{% block content %}
    <div class="forum">
        <h1>{% trans 'Last updates in topics' %}</h1>
        {% if forum.headline %}
            <div class="forum-headline alert alert-block">
                {{ forum.headline|safe }}
            </div>
        {% endif %}

        {% include "pybb/pagination.html" %}

        {% include "pybb/topic_list.html" %}

        {% include "pybb/pagination.html" %}

        {% if user.is_authenticated %}
            <div id="mark-all-as-read">
                <a href="{% url 'pybb:mark_all_as_read' %}">
                    {% trans 'Mark all topics as read' %}
                </a>
            </div>
        {% endif %}
    </div>
{% endblock content %}

pybb/templates/pybb/pagination.html
{% load i18n %}

{% if is_paginated %}
    <div class="pagination">
        <ul class="pagination">
            <li class="prev {% if not page_obj.has_previous %}disabled{% endif %} px-2">
                <a href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}">← {% trans 'Previous page' %}</a>
            </li>
            {% for page in page_obj.pages %}
                {% if page %}
                    <li {% ifequal page page_obj.number %}class="disabled px-1"{% endifequal %}>
                       <a href="?{{ page.querystring }}" class="page px-1">{{ page }}</a>
                    </li>
                {% else %}
                    <li class="disabled">
                       <a href="#">...</a>
                    </li>
                {% endif %}
            {% endfor %}
            <li class="next {% if not page_obj.has_next %}disabled{% endif %} px-2">
                <a href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% endif %}" >{% trans 'Next page' %} →</a>
            </li>
        </ul>
    </div>
{% endif %}