account/urls.py
from django.conf.urls import url
from . import views

app_name = 'account'
urlpatterns = [
    url(r'^settings/(?P<pk>[0-9]+)/$', views.Settings.as_view(), name='settings'),
    url(r'^settings/password/$', views.password, name='password'),
    url(r'^sign_up/$', views.user_sign_up, name='sign_up'),
]

news/urls.py
from django.conf.urls import url
from . import views

app_name = 'news'
urlpatterns = [
    url(r'^(?P<page>[0-9]+)/$', views.Index.as_view(), name='index'),
    url(r'^filter/(?P<option>.+)/(?P<variable>.+)/$', views.CategoryTagView.as_view(), name='filter'),
    url(r'^detail/(?P<pk>[0-9]+)/$', views.Detail.as_view(), name='detail'),
    url(r'(?P<article_id>[0-9]+)/add_comment', views.add_comment, name='add_comment'),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from news import views  # Django freaks because no top level import like from ../news import views
from project.settings import TEMPLATE_PREFIX as TP

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^news/', include('news.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='account/'+TP+'/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name='news/'+TP+'/index.html'), name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'about/$', views.about, name='about'),
    url(r'contact_us/', views.contact_us, name='contact_us'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models
# Create your models here.
TITLE_MAX_LENGTH = 90
TAG_MAX_LENGTH = 30


class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    pub_date = models.DateTimeField()
    article_text = models.TextField()
    image_url = models.URLField(default='media/article_images/default.jpg')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return "\n Title: %s \n Publication date: %s \n Category: %s" % \
                (self.title, self.pub_date, self.category.name)


class Tags(models.Model):
    tag = models.CharField(max_length=TAG_MAX_LENGTH)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str__(self):
        return "TAG: %s ARTICLE: %s" % (self.tag, self.article.title)

news/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from .models import Article, Category, Tags
from django.db import Error
from django.utils.datastructures import MultiValueDictKeyError
from django.contrib.auth.decorators import login_required
from project.settings import TEMPLATE_PREFIX as TP

# Create your views here.


class Index(generic.ListView):

    model = Article
    allow_empty = True
    template_name = "news/"+TP+"/index.html"
    context_object_name = "articles"
    paginate_by = 10

    def get_queryset(self):
        return Article.objects.order_by('-pub_date')

    # def get_context_data(self, **kwargs):
    #     context = super(ArticleListView, self).get_context_data(**kwargs)
    #     context['now'] = timezone.now()
    #     return context TODO: for complex view


class Detail(generic.DetailView):

    model = Article
    template_name = "news/"+TP+"/detail.html"
    context_object_name = "article"

    # def get_context_data(self, **kwargs):
    #     context = super(Detail, self).get_context_data(**kwargs)
    #     #context['article'] = context['article'].comment_set.order_by('-pub_date')
    #     return context


class CategoryTagView(generic.ListView):

    model = Article
    allow_empty = True
    template_name = "news/"+TP+"/index.html"
    context_object_name = "articles"
    paginate_by = 10

    def get_queryset(self):
        if self.kwargs['option'] == 'category':
            cat = Category.objects.get(name=str(self.kwargs['variable']))
            return Article.objects.filter(category=cat).order_by('-pub_date')
        elif self.kwargs['option'] == 'tag':
            return Article.objects.filter(tags__tag=self.kwargs['variable']).order_by('-pub_date')

@login_required
def add_comment(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    if request.POST['comment_text'] == '':
        return render(request, 'news/'+TP+'/detail.html', {
            'article': article,
            'error_message': "You didn't enter text.",
        })
    else:
        try:
            article.comment_set.create(author=request.user.username, comment_text=request.POST['comment_text'],
                                       pub_date=timezone.now())
            article.save()
            return HttpResponseRedirect(reverse('news:detail', args=(article_id,)))
        except Error:
            return render(request, 'news/'+TP+'/detail.html', {
                'article': article,
                'error_message': "Can't add comment.",
            })


def about(request):
    return render(request, 'site/'+TP+'/about.html')


def contact_us(request):
    return render(request, 'site/' + TP + '/contact_us.html')

news/templates/site/base_v0/about.html
{% extends "../../site/base_v0/base.html" %}

{% block meta_description %} About Page PROJECT T.A.N.G.O. (game news) - fast loading game news website {% endblock %}

{% block title %} About Page PROJECT T.A.N.G.O. (game news) - fast loading game news website {% endblock %}

{% block main %}
{% load static %}
<section class="row justify-content-center">
    <div class="col-12 align-items-center">
        <h2>Welcome to Project T.A.N.G.O (game news)!</h2>
        <p>It's developed as fast-loading (almost without js or flash) web site with game news!</p>
        <p>Main reason for creating this web site was to work with Django framework. It's an open-source project, so
        if you are interested in it - go at https://github.com/stPhoenix/projecttango.</p>
        <p>Also, we want to dive in CI and CLI. So, we choose <a href="http://heroku.com/" >heroku</a> for app hosting
            and <a href="https://travis-ci.org/" >travis</a> for CI.</p>
        <p>If you have something to say - write to us.</p>

    </div>

</section>
{% endblock %}
{% block sidebar %}
{% endblock %}

news/templates/site/base_v0/base.html
<!DOCTYPE html>
<html lang="en" prefix="og: http://ogp.me/ns#">
<head>
  {% load static %}
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'news/base_v0/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'news/base_v0/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'news/base_v0/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'news/base_v0/favicon/manifest.json' %}">
    <link rel="mask-icon" href="{% static 'news/base_v0/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">
    <!-- Add bootstrap-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'news/base_v0/css/style.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block meta_description %} PROJECT T.A.N.G.O. (game news) - fast loading game news website {% endblock %}">
    <title> {% block title %} PROJECT T.A.N.G.O. (game news) - fast loading game news website {% endblock %}</title>
    {% block og_seo %}
      <meta property="og:title" content=" PROJECT T.A.N.G.O. (game news) - fast loading game news website" />
      <meta property="og:type" content="website" />
      <meta property="og:url" content="{% url 'index' %}" />
      <meta property="og:image" content="{% static 'news/base_v0/logo.jpg' %}" />
  {% endblock %}
</head>
<body>
 <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-12 card px-0 mx-0">
        <section class="card-body">
          <header class="row">
            <a href="{% url 'index' %}">
            <section class="col-12 col-md-10 col-lg-8 d-flex align-items-center">
              <img class="img-fluid" src="{% static 'news/base_v0/logo.jpg' %}" alt="logo image">
              <!--<h3 class="display-3 float-center align-middle logo-font">PROJECT T.A.N.G.O.</h3>
              <h3 class="text-right pb-4">(game news)</h3>-->
            </section>
            </a>
          </header>
          <nav class="row" aria-label="Navigation">
            <section class="d-inline-flex col-md-12 justify-content-center justify-content-lg-between flex-wrap flex-lg-nowrap hidden-scrolling">
              <ul class="list-unstyled navbar navbar-expand h4 nav-scrolling hidden-scrolling">
                <li class="nav-item">
                  <a href="{% url 'index' %}" class="border-bottom-line px-1">Home</a>
                </li>
                <li class="nav-item">
                  <a href="#" class="border-bottom-line px-1">Forum</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'about' %}" class="border-bottom-line px-1">About</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'contact_us' %}" class="border-bottom-line px-1">Contact<nobr> Us </nobr></a>
                </li>
              </ul>
              <ul class="list-unstyled navbar navbar-expand h4 nav-scrolling">
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a href="{% url 'index' %}" class="border-bottom-line px-1"><nobr>Welcome {{user.username}}</nobr></a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'account:settings' user.pk %}" class="border-bottom-line px-1">Settings</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'logout'%}" class="border-bottom-line px-1"><nobr> Log out </nobr></a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a href="{% url 'index' %}" class="border-bottom-line px-1"><nobr> Welcome Guest</nobr></a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'login'%}" class="border-bottom-line px-1"><nobr> Log in</nobr></a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'account:sign_up'%}" class="border-bottom-line px-1"><nobr> Sign up</nobr></a>
                </li>
                {% endif %}
              </ul>
            </section>
          </nav>
          <main class="row d-flex flex-column flex-lg-row justify-content-center mt-md-2">
            <div class="col-12 col-lg-8">
            {% block main %}
            <section class="row justify-content-center">
            <div class="col-8 d-flex align-items-center">
              <ul class="list-unstyled">
                <li>
                  <article>
                    <section class="row justify-content-center">
                      <div class="col-12 d-flex flex-nowrap justify-content-center">
                        <h5 class="my-0 border-bottom-line px-4">NEWS TITLE NEWS TITLE NEWS TITLE NEWS TITLE NEWS TITLE NEWS TITLE</h5>
                      </div>
                    </section>
                    <section class="row">
                      <div class="col-12 d-flex flex-nowrap">
                        <h6 class="p-1 pl-3 small">Category:xxxx</h6>
                        <h6 class="p-1 small">Tags:xxxx</h6>
                        <h6 class="p-1 small">Comments:xxxx</h6>
                      </div>
                    </section>
                    <section class="row">
                      <div class="col-12 d-flex px-4 mx-2">
                        <img class="img-fluid align-self-start w-25 border-img" src="ico.jpg" alt="logo image">
                        <p class="px-1">Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text  Text Text Text Text Text Text Text
                             Text Text Text Text Text Text Text
                          <a href="#">Continue read -></a>
                        </p>
                      </div>
                    </section>
                  </article>
              </ul>
            </div>
            </section>
            <section class="row">
              <div class="col-12 align-items-center">
                <nav aria-label="Pagination">
                <ul class="pagination pagination-xsm border-bottom-line">
                  <li class="page-item text-color-primary disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                  </li>
                  <li class="page-item"><a class="page-link" href="#">1</a></li>
                  <li class="page-item active">
                    <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="page-item "><a class="page-link" href="#">3</a></li>
                  <li class="page-item">
                    <a class="page-link" href="#">Next</a>
                  </li>
                 </ul>
              </nav>
              </div>
            </section>
            {% endblock %}
            </div>
            {% block sidebar %}
            <div class="col-12 col-lg-4 order-first order-lg-3">
              <h5 class="border-red p-lg-1">
                Welcome to Project T.A.N.G.O (game news)!
                It's developed as fast-loading (almost without js or flash)
                web site with game news!
                Visit our about page for more details.
              </h5>
            </div>
            {% endblock %}
          </main>
          <footer class="row">
            <section class="col-12 col-md-12 d-flex align-items-start">
              <p class="my-0">Copyright 2017 Project Tango PROJECT T.A.N.G.O. (game news) - fast loading game news website</p>
            </section>
          </footer>
        </section>
      </div>
    </div>
  </div>
</body>
</html>

news/templates/site/base_v0/contact_us.html
{% extends "../../site/base_v0/base.html" %}

{% block meta_description %} Contact Us Page PROJECT T.A.N.G.O. (game news) - fast loading game news website {% endblock %}

{% block title %} Contact Us Page PROJECT T.A.N.G.O. (game news) - fast loading game news website {% endblock %}

{% block main %}
{% load static %}
<section class="row justify-content-center">
    <div class="col-12 align-items-center">
        <h2>Welcome to Project T.A.N.G.O (game news)!</h2>
        <p>To contact us send your messages to saintdevs@gmail.com</p>

    </div>

</section>
{% endblock %}
{% block sidebar %}
{% endblock %}